/*
  Script: Scaffold per-component en.json files
  - Scans component source directories for .tsx files
  - Creates src/i18n/locales/components/<ComponentName>.en.json if missing
  - Adds a __status key and a root key matching the component (file base) name
*/

const fs = require('fs');
const path = require('path');

const projectRoot = process.cwd();
const srcDir = path.join(projectRoot, 'src');
const outputDir = path.join(srcDir, 'i18n', 'locales', 'components');

/**
 * Recursively walk a directory and collect .tsx files
 * @param {string} startDir
 * @param {(p: string) => boolean} filter
 * @returns {string[]}
 */
function collectTsxFiles(startDir, filter) {
  /** @type {string[]} */
  const results = [];
  /** @param {string} dir */
  function walk(dir) {
    let entries = [];
    try {
      entries = fs.readdirSync(dir, { withFileTypes: true });
    } catch (_) {
      return;
    }
    for (const entry of entries) {
      const fullPath = path.join(dir, entry.name);
      if (entry.isDirectory()) {
        walk(fullPath);
      } else if (entry.isFile() && entry.name.endsWith('.tsx')) {
        if (!filter || filter(fullPath)) {
          results.push(fullPath);
        }
      }
    }
  }
  walk(startDir);
  return results;
}

// Define which directories to scan
const scanTargets = [
  path.join(srcDir, 'components'),
  path.join(srcDir, 'app'),
];

// Filter: include files that are clearly components
// - Any under src/components
// - Any under folders named _components or sections within src/app
// - Exclude Next.js route pages named page.tsx and layout.tsx unless they live inside _components or sections
/** @param {string} p */
function isComponentPath(p) {
  const normalized = p.replace(/\\/g, '/');
  if (normalized.includes('/src/components/')) return true;
  if (normalized.includes('/_components/')) return true;
  if (normalized.includes('/sections/')) return true;
  const file = path.basename(p).toLowerCase();
  if (file === 'page.tsx' || file === 'layout.tsx') return false;
  return false;
}

// Ensure output directory exists
fs.mkdirSync(outputDir, { recursive: true });

// Collect all component files
const componentFiles = scanTargets.flatMap(target => collectTsxFiles(target, isComponentPath));

// Generate unique set by base name to avoid duplicates across directories
/** @type {Map<string, { name: string, files: string[] }>} */
const componentsByBase = new Map();
for (const filePath of componentFiles) {
  const base = path.basename(filePath, '.tsx');
  const existing = componentsByBase.get(base) || { name: base, files: [] };
  existing.files.push(filePath);
  componentsByBase.set(base, existing);
}

let created = 0;
let skipped = 0;

for (const { name } of componentsByBase.values()) {
  // File name can contain spaces and parentheses on Windows; keep as-is
  const outFile = path.join(outputDir, `${name}.en.json`);
  if (fs.existsSync(outFile)) {
    skipped++;
    continue;
  }
  const content = {
    __status: `complete: ${name} translations scaffolded`,
  };
  // Root key is the component base name (file name without extension)
  content[name] = {};
  // Write pretty JSON with 2 spaces
  fs.writeFileSync(outFile, JSON.stringify(content, null, 2) + '\n', 'utf8');
  created++;
}

// Generate index.en.ts that aggregates all JSONs for build-time import
const indexLines = [];
indexLines.push('// Auto-generated by scripts/scaffold-i18n.js');
indexLines.push('// Do not edit manually.');
indexLines.push('');
const exportEntries = [];
for (const { name } of Array.from(componentsByBase.values()).sort((a, b) => a.name.localeCompare(b.name))) {
  const safeImportName = name
    .replace(/[^A-Za-z0-9_]/g, '_')
    .replace(/^([0-9])/, '_$1');
  const relPath = `./${name}.en.json`;
  indexLines.push(`import ${safeImportName} from '${relPath}';`);
  exportEntries.push(safeImportName);
}
indexLines.push('');
indexLines.push('const componentsEn = Object.assign({}, ' + exportEntries.join(', ') + ');');
indexLines.push('');
indexLines.push('export default componentsEn;');

const indexFilePath = path.join(outputDir, 'index.en.ts');
fs.writeFileSync(indexFilePath, indexLines.join('\n') + '\n', 'utf8');

console.log(`Scaffold complete. Created: ${created}, Skipped: ${skipped}. Index generated for ${exportEntries.length} components.`);


